USE fx_todo;

CREATE TABLE IF NOT EXISTS goals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  deadline DATE DEFAULT NULL,
  status ENUM('active', 'completed', 'abandoned') DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE tasks ADD COLUMN goal_id INT DEFAULT NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_task_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE SET NULL;
